### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by LappleApple** [zalando-incubator/camunda-meets-cassandra#1]
Hey -- this HW project hasn't been touched in +1 year. Is there some instructional use for it, that people might find useful? If not, I'd deprecate/remove...

**Comment by harti2006** [comment]
From my point of view, it is deprecated. @jhorstmann what o you think about it?

**Comment by jhorstmann** [comment]
It might still be useful as an example on how to approach implementing a different persistence layer for the camunda process engine. We could maybe make this more clear in the README.

BTW, there is a similar project at https://github.com/camunda/camunda-engine-cassandra but it also looks like it wasn't updated recently.

**Comment by LappleApple** [comment]
@harti2006 @jhorstmann Hey guys, now that the incubator is up I would propose moving this repo to there. WDYT?

**Comment by LappleApple** [comment]
Thanks, @harti2006 . @jhorstmann, all we need is a green light from you :)

**Comment by jhorstmann** [comment]
:+1: let's move it to the incubator

**Comment by LappleApple** [comment]
done :)
